### ISSUE TITLE
请问可以考虑同步manjaro的源吗？

### ISSUE THREAD

**Issue by mise42** [zjulug/simple-mirrors-monitor#1]
manjaro是distrowatch上的排名第４～5名的linux发行版。基于arch，对新手更友好。中科大源小水管觉得还是有点慢，望考虑一下？十分感谢啦～

**Comment by vxst** [comment]
看上去不错，我近期加一下

我之前一直以为它还在beta stage...

> 在 2017年2月18日，11:20，saisunshine <notifications@github.com> 写道：
> 
> manjaro

**Comment by vxst** [comment]
@saisunshine 不出意外的话近几天应该会上线，以及以后类似的issue可以发到[IssueTracker](https://github.com/ZJU-NewMirrors/IssueTracker)，SimpleMirrorsMonitor的Issue主要用途是搜集SimpleMirrorsMonitor的bug...
